# Pandas

## DataFrame

### DataFrame 结构

In [5]:
import numpy as np
import pandas as pd

In [6]:
# 创建一个符合正态分布的 10 支股票 5 天内的涨跌幅数据
stock_change = np.random.normal(0, 1, (10, 5))

In [5]:
stock_change

array([[-0.46182992,  0.12019474, -1.15437614, -0.09053703,  0.17455913],
       [-0.20905998,  0.68518892,  1.1026634 ,  2.52573148, -1.73700414],
       [-2.30617559,  0.08013553,  0.28369232, -0.46207883,  0.71115346],
       [ 1.19196403,  0.24622009,  0.95572014,  0.1843441 ,  0.34857969],
       [-0.80852024,  0.2570339 , -0.22534932,  2.34169   , -0.94620692],
       [ 1.55849342,  1.57916403,  0.05742434, -1.14350354, -1.42569821],
       [ 1.04755591,  0.0580752 ,  0.14500976,  0.8815285 , -1.32614855],
       [-1.99741675,  0.58771186, -0.77941358, -0.620167  , -0.22863551],
       [ 0.53292115,  0.07138332,  0.15406709,  0.90393226, -1.79411439],
       [-0.43231582,  0.90681722,  0.07309412, -0.19639308,  0.45440386]])

In [7]:
# 用 pandas 创建
pd.DataFrame(stock_change)

0         1         2         3         4
0 -0.461830  0.120195 -1.154376 -0.090537  0.174559
1 -0.209060  0.685189  1.102663  2.525731 -1.737004
2 -2.306176  0.080136  0.283692 -0.462079  0.711153
3  1.191964  0.246220  0.955720  0.184344  0.348580
4 -0.808520  0.257034 -0.225349  2.341690 -0.946207
5  1.558493  1.579164  0.057424 -1.143504 -1.425698
6  1.047556  0.058075  0.145010  0.881528 -1.326149
7 -1.997417  0.587712 -0.779414 -0.620167 -0.228636
8  0.532921  0.071383  0.154067  0.903932 -1.794114
9 -0.432316  0.906817  0.073094 -0.196393  0.454404

In [16]:
# 添加行（index）索引
label_index = ['股票{}'.format(i) for i in range(10)]
label_index

['股票0', '股票1', '股票2', '股票3', '股票4', '股票5', '股票6', '股票7', '股票8', '股票9']

In [17]:
pd.DataFrame(stock_change, index=label_index)

0         1         2         3         4
股票0 -0.461830  0.120195 -1.154376 -0.090537  0.174559
股票1 -0.209060  0.685189  1.102663  2.525731 -1.737004
股票2 -2.306176  0.080136  0.283692 -0.462079  0.711153
股票3  1.191964  0.246220  0.955720  0.184344  0.348580
股票4 -0.808520  0.257034 -0.225349  2.341690 -0.946207
股票5  1.558493  1.579164  0.057424 -1.143504 -1.425698
股票6  1.047556  0.058075  0.145010  0.881528 -1.326149
股票7 -1.997417  0.587712 -0.779414 -0.620167 -0.228636
股票8  0.532921  0.071383  0.154067  0.903932 -1.794114
股票9 -0.432316  0.906817  0.073094 -0.196393  0.454404

In [21]:
# 添加列（columns）索引
date = pd.date_range(start='20220101', periods=5, freq='B')

In [22]:
date

DatetimeIndex(['2022-01-03', '2022-01-04', '2022-01-05', '2022-01-06',
               '2022-01-07'],
              dtype='datetime64[ns]', freq='B')

In [25]:
stock_change = pd.DataFrame(stock_change, index=label_index, columns=date)
stock_change

2022-01-03  2022-01-04  2022-01-05  2022-01-06  2022-01-07
股票0   -0.461830    0.120195   -1.154376   -0.090537    0.174559
股票1   -0.209060    0.685189    1.102663    2.525731   -1.737004
股票2   -2.306176    0.080136    0.283692   -0.462079    0.711153
股票3    1.191964    0.246220    0.955720    0.184344    0.348580
股票4   -0.808520    0.257034   -0.225349    2.341690   -0.946207
股票5    1.558493    1.579164    0.057424   -1.143504   -1.425698
股票6    1.047556    0.058075    0.145010    0.881528   -1.326149
股票7   -1.997417    0.587712   -0.779414   -0.620167   -0.228636
股票8    0.532921    0.071383    0.154067    0.903932   -1.794114
股票9   -0.432316    0.906817    0.073094   -0.196393    0.454404

### DataFrame 属性

In [27]:
# 形状
stock_change.shape  # (10, 5)

(10, 5)

In [29]:
# 行索引
stock_change.index  # Index(['股票0', '股票1', '股票2', '股票3', '股票4', '股票5', '股票6', '股票7', '股票8', '股票9'], dtype='object')

Index(['股票0', '股票1', '股票2', '股票3', '股票4', '股票5', '股票6', '股票7', '股票8', '股票9'], dtype='object')

In [30]:
# 列索引
stock_change.columns  

DatetimeIndex(['2022-01-03', '2022-01-04', '2022-01-05', '2022-01-06',
               '2022-01-07'],
              dtype='datetime64[ns]', freq='B')

In [31]:
# 去除行列索引（ndarry）
stock_change.values

array([[-0.46182992,  0.12019474, -1.15437614, -0.09053703,  0.17455913],
       [-0.20905998,  0.68518892,  1.1026634 ,  2.52573148, -1.73700414],
       [-2.30617559,  0.08013553,  0.28369232, -0.46207883,  0.71115346],
       [ 1.19196403,  0.24622009,  0.95572014,  0.1843441 ,  0.34857969],
       [-0.80852024,  0.2570339 , -0.22534932,  2.34169   , -0.94620692],
       [ 1.55849342,  1.57916403,  0.05742434, -1.14350354, -1.42569821],
       [ 1.04755591,  0.0580752 ,  0.14500976,  0.8815285 , -1.32614855],
       [-1.99741675,  0.58771186, -0.77941358, -0.620167  , -0.22863551],
       [ 0.53292115,  0.07138332,  0.15406709,  0.90393226, -1.79411439],
       [-0.43231582,  0.90681722,  0.07309412, -0.19639308,  0.45440386]])

In [37]:
# 转置
stock_change.T

股票0       股票1       股票2       股票3       股票4       股票5  \
2022-01-03 -0.461830 -0.209060 -2.306176  1.191964 -0.808520  1.558493   
2022-01-04  0.120195  0.685189  0.080136  0.246220  0.257034  1.579164   
2022-01-05 -1.154376  1.102663  0.283692  0.955720 -0.225349  0.057424   
2022-01-06 -0.090537  2.525731 -0.462079  0.184344  2.341690 -1.143504   
2022-01-07  0.174559 -1.737004  0.711153  0.348580 -0.946207 -1.425698   

                 股票6       股票7       股票8       股票9  
2022-01-03  1.047556 -1.997417  0.532921 -0.432316  
2022-01-04  0.058075  0.587712  0.071383  0.906817  
2022-01-05  0.145010 -0.779414  0.154067  0.073094  
2022-01-06  0.881528 -0.620167  0.903932 -0.196393  
2022-01-07 -1.326149 -0.228636 -1.794114  0.454404

### DataFrame 的方法

In [34]:
# 返回前 n 行数据，参数中如果不指定，默认是 5 行
stock_change.head(3)

2022-01-03  2022-01-04  2022-01-05  2022-01-06  2022-01-07
股票0   -0.461830    0.120195   -1.154376   -0.090537    0.174559
股票1   -0.209060    0.685189    1.102663    2.525731   -1.737004
股票2   -2.306176    0.080136    0.283692   -0.462079    0.711153

In [36]:
# 返回后 n 行数据，参数中如果不指定，默认是 5 行
stock_change.tail(2)

2022-01-03  2022-01-04  2022-01-05  2022-01-06  2022-01-07
股票8    0.532921    0.071383    0.154067    0.903932   -1.794114
股票9   -0.432316    0.906817    0.073094   -0.196393    0.454404

### DatatFrame 索引的设置

In [7]:
stock_change

array([[-1.89603349, -0.65551458,  1.1349849 , -0.92412679,  0.56509563],
       [ 0.99941057,  0.37215663, -0.50656232, -1.4921113 ,  0.24875855],
       [ 0.9338103 ,  0.27277976, -0.88424288, -0.78060492, -0.28401107],
       [-0.25009889, -0.62984548, -0.26301601,  1.01470854,  0.74803886],
       [ 0.21261477, -0.30164156,  1.29518867, -1.56721449, -1.32912768],
       [ 0.72032196, -0.72121603, -0.26940467, -0.06614891, -0.87494215],
       [-0.73042158,  1.5230075 , -0.28910817,  1.44657023, -0.42243231],
       [ 1.96209728, -1.3663957 , -0.03318994,  0.83111296, -1.17703668],
       [ 1.22590161, -0.50922545, -0.42851618, -1.13063256, -0.22594933],
       [-0.61688931,  1.14076485,  0.29649072, -1.00551766,  1.49456875]])

In [10]:
data = pd.DataFrame(stock_change)

data

0         1         2         3         4
0 -1.896033 -0.655515  1.134985 -0.924127  0.565096
1  0.999411  0.372157 -0.506562 -1.492111  0.248759
2  0.933810  0.272780 -0.884243 -0.780605 -0.284011
3 -0.250099 -0.629845 -0.263016  1.014709  0.748039
4  0.212615 -0.301642  1.295189 -1.567214 -1.329128
5  0.720322 -0.721216 -0.269405 -0.066149 -0.874942
6 -0.730422  1.523008 -0.289108  1.446570 -0.422432
7  1.962097 -1.366396 -0.033190  0.831113 -1.177037
8  1.225902 -0.509225 -0.428516 -1.130633 -0.225949
9 -0.616889  1.140765  0.296491 -1.005518  1.494569

- 修改行列索引值

In [17]:
# 必须全部修改
label = ['股票_{}'.format(i) for i in range(10)]
label

['股票_0',
 '股票_1',
 '股票_2',
 '股票_3',
 '股票_4',
 '股票_5',
 '股票_6',
 '股票_7',
 '股票_8',
 '股票_9']

In [19]:
data.index = label
data

0         1         2         3         4
股票_0 -1.896033 -0.655515  1.134985 -0.924127  0.565096
股票_1  0.999411  0.372157 -0.506562 -1.492111  0.248759
股票_2  0.933810  0.272780 -0.884243 -0.780605 -0.284011
股票_3 -0.250099 -0.629845 -0.263016  1.014709  0.748039
股票_4  0.212615 -0.301642  1.295189 -1.567214 -1.329128
股票_5  0.720322 -0.721216 -0.269405 -0.066149 -0.874942
股票_6 -0.730422  1.523008 -0.289108  1.446570 -0.422432
股票_7  1.962097 -1.366396 -0.033190  0.831113 -1.177037
股票_8  1.225902 -0.509225 -0.428516 -1.130633 -0.225949
股票_9 -0.616889  1.140765  0.296491 -1.005518  1.494569

In [21]:
# 不能直接用列表索引的方式修改！
data.index[3] = '股票四'

TypeError: Index does not support mutable operations

- **重设索引**

In [22]:
data.reset_index()

index         0         1         2         3         4
0  股票_0 -1.896033 -0.655515  1.134985 -0.924127  0.565096
1  股票_1  0.999411  0.372157 -0.506562 -1.492111  0.248759
2  股票_2  0.933810  0.272780 -0.884243 -0.780605 -0.284011
3  股票_3 -0.250099 -0.629845 -0.263016  1.014709  0.748039
4  股票_4  0.212615 -0.301642  1.295189 -1.567214 -1.329128
5  股票_5  0.720322 -0.721216 -0.269405 -0.066149 -0.874942
6  股票_6 -0.730422  1.523008 -0.289108  1.446570 -0.422432
7  股票_7  1.962097 -1.366396 -0.033190  0.831113 -1.177037
8  股票_8  1.225902 -0.509225 -0.428516 -1.130633 -0.225949
9  股票_9 -0.616889  1.140765  0.296491 -1.005518  1.494569

In [24]:
data

0         1         2         3         4
股票_0 -1.896033 -0.655515  1.134985 -0.924127  0.565096
股票_1  0.999411  0.372157 -0.506562 -1.492111  0.248759
股票_2  0.933810  0.272780 -0.884243 -0.780605 -0.284011
股票_3 -0.250099 -0.629845 -0.263016  1.014709  0.748039
股票_4  0.212615 -0.301642  1.295189 -1.567214 -1.329128
股票_5  0.720322 -0.721216 -0.269405 -0.066149 -0.874942
股票_6 -0.730422  1.523008 -0.289108  1.446570 -0.422432
股票_7  1.962097 -1.366396 -0.033190  0.831113 -1.177037
股票_8  1.225902 -0.509225 -0.428516 -1.130633 -0.225949
股票_9 -0.616889  1.140765  0.296491 -1.005518  1.494569

In [25]:
data.reset_index(drop=True)

0         1         2         3         4
0 -1.896033 -0.655515  1.134985 -0.924127  0.565096
1  0.999411  0.372157 -0.506562 -1.492111  0.248759
2  0.933810  0.272780 -0.884243 -0.780605 -0.284011
3 -0.250099 -0.629845 -0.263016  1.014709  0.748039
4  0.212615 -0.301642  1.295189 -1.567214 -1.329128
5  0.720322 -0.721216 -0.269405 -0.066149 -0.874942
6 -0.730422  1.523008 -0.289108  1.446570 -0.422432
7  1.962097 -1.366396 -0.033190  0.831113 -1.177037
8  1.225902 -0.509225 -0.428516 -1.130633 -0.225949
9 -0.616889  1.140765  0.296491 -1.005518  1.494569

- **将某列设置为新索引**



In [29]:
# 【重点】如果以字典的形式传入，字典的 value 默认会作为列名出现！
data = pd.DataFrame({'month': [1, 4, 7, 10],
                    'year': [2012, 2014, 2013, 2014],
                    'sale':[55, 40, 84, 31]})

data

month  year  sale
0      1  2012    55
1      4  2014    40
2      7  2013    84
3     10  2014    31

In [40]:
# 将 month 设置为新索引
tmp = data.set_index('month')
tmp

year  sale
month            
1      2012    55
4      2014    40
7      2013    84
10     2014    31

In [41]:
tmp.index

Int64Index([1, 4, 7, 10], dtype='int64', name='month')

In [31]:
data.set_index('month', drop=False)

month  year  sale
month                   
1          1  2012    55
4          4  2014    40
7          7  2013    84
10        10  2014    31

** 与此同时，如果设置多个列为索引，这样DataFrame就变成了一个具有MultiIndex的DataFrame。**

In [33]:
type(data.index)

pandas.core.indexes.range.RangeIndex

In [43]:
# 	**与此同时，如果设置多个列为索引，这样DataFrame就变成了一个具有MultiIndex的DataFrame。**
tmp = data.set_index(['month', 'year'])
tmp

sale
month year      
1     2012    55
4     2014    40
7     2013    84
10    2014    31

In [44]:
tmp.index

MultiIndex([( 1, 2012),
            ( 4, 2014),
            ( 7, 2013),
            (10, 2014)],
           names=['month', 'year'])


## MultiIndex 与 Panel

### MultiIndex

MultiIndex 是**三维的数据结构**;

**多级索引（也称层次化索引）是 pandas 的重要功能，可以在 Series、DataFrame 对象上拥有 2个以及2个以上的索引。**

In [45]:
tmp.index

MultiIndex([( 1, 2012),
            ( 4, 2014),
            ( 7, 2013),
            (10, 2014)],
           names=['month', 'year'])

In [47]:
tmp.index.names

FrozenList(['month', 'year'])

In [48]:
tmp.index.levels

FrozenList([[1, 4, 7, 10], [2012, 2013, 2014]])

**MultiIndex 的创建**


In [57]:
arrays = [[1, 1, 2, 2], ['red', 'blue', 'red', 'blue']]
pd.MultiIndex.from_arrays(arrays, names=('number', 'color'))

MultiIndex([(1,  'red'),
            (1, 'blue'),
            (2,  'red'),
            (2, 'blue')],
           names=['number', 'color'])

## Series

Series 是一个类似于**一维数组**的数据结构，它能够保存任何类型的数据，比如整数、字符串、浮点数等，**主要由一组数据和与之相关的索引两部分构成。**

<img src="doc/pic/README/image-20220205222205344.png" alt="image-20220205222205344" style="zoom:50%;" />

### Series 的创建

```python
# 导入pandas
import pandas as pd

pd.Series(data=None, index=None, dtype=None)
```

- 参数：
    - `data`：传入的数据，可以是ndarray、list等
    - `index`：索引，必须是唯一的，且与数据的长度相等。如果没有传入索引参数，则默认会自动创建一个从0-N的整数索引。
    - `dtype`：数据的类型




**通过已有数据创建**

In [59]:
pd.Series(np.arange(10))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

**指定索引**

In [60]:
pd.Series([6.7,5.6,3,10,2], index=[1,2,3,4,5])

1     6.7
2     5.6
3     3.0
4    10.0
5     2.0
dtype: float64

**通过字典数据创建**

In [61]:
color_count = pd.Series({'red':100, 'blue':200, 'green': 500, 'yellow':1000})
color_count

red        100
blue       200
green      500
yellow    1000
dtype: int64

### Series 的属性

为了更方便地操作 Series 对象中的索引和数据，**Series 中提供了两个属性 index 和 values**

In [63]:
color_count.index

Index(['red', 'blue', 'green', 'yellow'], dtype='object')

In [64]:
color_count.values

array([ 100,  200,  500, 1000])

**使用索引来获取数据**

In [67]:
color_count[2]

500

## 基本数据操作



### 索引

Numpy 当中我们已经讲过使用索引选取序列和切片选择，pandas 也支持类似的操作，也可以直接使用列名、行名称，甚至组合使用。



| 方法                                                         | 描述                                                |
| ------------------------------------------------------------ | --------------------------------------------------- |
| `DataFrame['列名']['行名']`                                  | 直接使用行列名称索引<br />**注意：先列后行**        |
| `DataFrame.loc['行名']['列名']`<br />`DataFrame.loc['行名', '列名']` | 如果使用名称索引且**先行后列**                      |
| `DataFrame.iloc[index][colnums]`<br />`DataFrame.iloc['行名', '列名']` | 使用**下标**索引且**先行后列**                      |
| `DataFrame.ix[下标或名称, 下标或名称]`                       | **ix组合索引**；注意，0.20.0 之后的版本可能不再支持 |



---







In [69]:
# 读取文件
data = pd.read_csv('./data/stock_day/stock_day.csv')

# 删除一些列，让数据更简单些，再去做后面的操作，axis= 表示按列删除
data = data.drop(["ma5","ma10","ma20","v_ma5","v_ma10","v_ma20"], axis=1)

In [72]:
data

open   high  close    low     volume  price_change  p_change  \
2018-02-27  23.53  25.88  24.16  23.53   95578.03          0.63      2.68   
2018-02-26  22.80  23.78  23.53  22.80   60985.11          0.69      3.02   
2018-02-23  22.88  23.37  22.82  22.71   52914.01          0.54      2.42   
2018-02-22  22.25  22.76  22.28  22.02   36105.01          0.36      1.64   
2018-02-14  21.49  21.99  21.92  21.48   23331.04          0.44      2.05   
...           ...    ...    ...    ...        ...           ...       ...   
2015-03-06  13.17  14.48  14.28  13.13  179831.72          1.12      8.51   
2015-03-05  12.88  13.45  13.16  12.87   93180.39          0.26      2.02   
2015-03-04  12.80  12.92  12.90  12.61   67075.44          0.20      1.57   
2015-03-03  12.52  13.06  12.70  12.52  139071.61          0.18      1.44   
2015-03-02  12.25  12.67  12.52  12.20   96291.73          0.32      2.62   

            turnover  
2018-02-27      2.39  
2018-02-26      1.53  
2018-02-23      1.32  
2018-02-22      0.90  
2018-02-14      0.58  
...              ...  
2015-03-06      6.16  
2015-03-05      3.19  
2015-03-04      2.30  
2015-03-03      4.76  
2015-03-02      3.30  

[643 rows x 8 columns]

直接使用行列名称索引

**注意：先列后行**

In [77]:
data['close']['2018-02-23']

22.82

In [80]:
# data['close', '2018-02-23'] ERROR

KeyError: ('close', '2018-02-23')

使用 loc 只能指定行列索引的名字

In [84]:
data.loc['2018-02-27':'2018-02-22']['open']

2018-02-27    23.53
2018-02-26    22.80
2018-02-23    22.88
2018-02-22    22.25
Name: open, dtype: float64

In [85]:
data.loc['2018-02-27':'2018-02-22', 'open']

2018-02-27    23.53
2018-02-26    22.80
2018-02-23    22.88
2018-02-22    22.25
Name: open, dtype: float64

使用**下标**索引且**先行后列**

In [90]:
# 使用iloc可以通过索引的下标去获取
# 获取前3天数据,前5列的结果
data.iloc[:3][:5] 但是这种好像有点问题，输出不是前 5 列

open   high  close    low    volume  price_change  p_change  \
2018-02-27  23.53  25.88  24.16  23.53  95578.03          0.63      2.68   
2018-02-26  22.80  23.78  23.53  22.80  60985.11          0.69      3.02   
2018-02-23  22.88  23.37  22.82  22.71  52914.01          0.54      2.42   

            turnover  
2018-02-27      2.39  
2018-02-26      1.53  
2018-02-23      1.32

In [86]:
# 使用iloc可以通过索引的下标去获取
# 获取前3天数据,前5列的结果
data.iloc[:3, :5]

open   high  close    low    volume
2018-02-27  23.53  25.88  24.16  23.53  95578.03
2018-02-26  22.80  23.78  23.53  22.80  60985.11
2018-02-23  22.88  23.37  22.82  22.71  52914.01

【已废弃】使用ix组合索引

Warning:Starting in 0.20.0, the .ix indexer is deprecated, in favor of the more strict .iloc and .loc indexers.

获取行第1天到第4天，['open', 'close', 'high', 'low']这个四个指标的结果

In [87]:
# 使用ix进行下表和名称组合做引
data.ix[0:4, ['open', 'close', 'high', 'low']]

AttributeError: 'DataFrame' object has no attribute 'ix'

In [88]:
# 推荐使用loc和iloc来获取的方式
data.loc[data.index[0:4], ['open', 'close', 'high', 'low']]
data.iloc[0:4, data.columns.get_indexer(['open', 'close', 'high', 'low'])]

open  close   high    low
2018-02-27  23.53  24.16  25.88  23.53
2018-02-26  22.80  23.53  23.78  22.80
2018-02-23  22.88  22.82  23.37  22.71
2018-02-22  22.25  22.28  22.76  22.02

### 赋值操作

- 将 DataFrame 中的某一列都修改为一个指定的值

In [92]:
data.head()

open   high  close    low    volume  price_change  p_change  \
2018-02-27  23.53  25.88  24.16  23.53  95578.03          0.63      2.68   
2018-02-26  22.80  23.78  23.53  22.80  60985.11          0.69      3.02   
2018-02-23  22.88  23.37  22.82  22.71  52914.01          0.54      2.42   
2018-02-22  22.25  22.76  22.28  22.02  36105.01          0.36      1.64   
2018-02-14  21.49  21.99  21.92  21.48  23331.04          0.44      2.05   

            turnover  
2018-02-27      2.39  
2018-02-26      1.53  
2018-02-23      1.32  
2018-02-22      0.90  
2018-02-14      0.58

In [93]:
data['open']

2018-02-27    23.53
2018-02-26    22.80
2018-02-23    22.88
2018-02-22    22.25
2018-02-14    21.49
              ...  
2015-03-06    13.17
2015-03-05    12.88
2015-03-04    12.80
2015-03-03    12.52
2015-03-02    12.25
Name: open, Length: 643, dtype: float64

In [96]:
# 方法 1
data['open'] = 66
data.head()


open   high  close    low    volume  price_change  p_change  \
2018-02-27    66  25.88  24.16  23.53  95578.03          0.63      2.68   
2018-02-26    66  23.78  23.53  22.80  60985.11          0.69      3.02   
2018-02-23    66  23.37  22.82  22.71  52914.01          0.54      2.42   
2018-02-22    66  22.76  22.28  22.02  36105.01          0.36      1.64   
2018-02-14    66  21.99  21.92  21.48  23331.04          0.44      2.05   

            turnover  
2018-02-27      2.39  
2018-02-26      1.53  
2018-02-23      1.32  
2018-02-22      0.90  
2018-02-14      0.58